---
title: "Simplify ANAEs for plotting"
format: html
editor: visual
---

```{r}
source('directorySet.R')
library(CC2)
library(sf)
library(foreach)
library(doFuture)
library(progressr)
```

```{r}
if (parset == 'local') {
  plan(multisession)
}

# These take a REALLY long time
if (parset == 'gandalf') {
  plan(list(tweak(future.batchtools::batchtools_slurm,
                template = "batchtools.slurm.tmpl",
                resources = list(time = 1200,
                                 ntasks.per.node = 12, 
                                 mem = "70GB",
                                 job.name = 'daily1030')),
          multicore))
}
```

```{r}
source('R/anae_simplify.R')
with_progress({
  out_tib <- process_with_checks(
                          process_function = 'anae_simplify',
                          catchment = 'all',
                          out_dir = datOut,
                          nchunks = 1)
})
```

There's an issue with the bidgee- set a breakpoint and work through finding it.

```{r}
# anaes_simple <- rmapshaper::ms_simplify(anaes[1:10000, ],
#                                           keep = keep, 
#                                         keep_shapes = 
#                                           keep_shapes, 
#                                         explode = explode)
```

Read in and bind

```{r}
all_simple_files <- list.files(file.path(datOut, 'anae_simplify'), pattern = '.rds')

all_simple_anae <- purrr::map(all_simple_files, \(x) readRDS(file.path(datOut, 'anae_simplify', x)))

all_simple_tib <- all_simple_anae |>
  dplyr::bind_rows()

saveRDS(all_simple_tib, file.path(datOut, 'anae_simplify', 'all_anae_simplify.rds'))
```
