---
title: "Overview of SRA analyses"
format: html
editor: visual
---

## Workflow

### Getting started

The work is all done in the [SRA repo](https://github.com/galenholt/SRA). It has a renv, but renv keeps being annoying about github, so you might have to manually install that and then do the usual `renv::install()`.

`{r}} #| eval: false renv::install('git@github.com:galenholt/CC2.git@dev', rebuild = TRUE, upgrade = 'always', git = 'external', prompt = FALSE)`

All input data is in `QAEL - MER/Model/dataBase` . Processing uses *the dev branch of* [eFlowEval](https://github.com/galenholt/CC2) - you'll need to install that, it comes with some canonical data and processing functions.

### Notebooks

The notebooks here do data processing and analysis for SRA for three questions

1.  Waterbird breeding opportunity

2.  Diversity of inundated wetlands

3.  Vegetation growth opportunity

I've numbered them in order to be run. The ones that assess inundation should be run on the HPC, and likely some others as well. If you want to run on the HPC, it's probably easiest to set up a single loop that does what you want and then talk to me.

In general, the sequence is

-   Create a set of relevant ANAES (split by catchment, put into bird wetlands, etc)

-   Put inundation or other data into ANAEs

-   Assess responses to the inundation in those ANAEs.
