---
title: "Lignum runs"
format: html
editor: visual
---

I've gone with separate qmds for each species just to make it easier to do one-off runs. They're all just copy-pastes of each other though.

```{r}
source('directorySet.R')
library(CC2)
library(foreach)
library(doFuture)
library(progressr)
doFuture::registerDoFuture()
```

```{r}
if (parset == 'local') {
  plan(multisession)
}

if (parset == 'gandalf') {
  plan(multicore)
  # plan(list(tweak(future.batchtools::batchtools_slurm,
  #               template = "batchtools.slurm.tmpl",
  #               resources = list(time = 60,
  #                                ntasks.per.node = 5,
  #                                mem = "70GB",
  #                                job.name = 'lignum')),
  #         multicore))
}
```

Set up. I'm still trying to decide how much of this is general and how much bespoke.

```{r}
# should move to eFlowEval
source('R/woody_general.R')
source('R/lignum.R')

with_progress({
  out_tib <- process_with_checks(
                          process_function = 'lignum',
                          catchment = 'all',
                          out_dir = datOut,
                          nchunks = 1)
})

```

```{r}
out_tib$timings
```
