---
title: "Woody Veg Methods"
format: html
editor: visual
bibliography: references.bib
---

# Methods

We model four iconic species of woody vegetation in the Murray-Darling Basin, Red Gum (*Eucalyptus camaldulensis*), Black Box (*Eucalyptus largiflorens*), Coolabah (*Eucalyptus coolabah*), and Lignum (*Muehlenbeckia florulenta*). We consider two approaches to assess favourability for woody vegetation in wetlands, as well as their combination. One approach is to consider the amount of inundation in wetlands of different habitat types, with inundation into the 'correct' habitat type for a species yielding favourable conditions. The other is to use models that capture biological processes to ask whether environmental conditions were favourable for those processes. Finally, we can combine the two, and ask whether environmental conditions were favourable for biological processes to occur in areas of 'correct' habitat.

*We need something here about the logic of comparisons, but that might wait until we firm those comparisons up.*

## Biological favourability

Biological, process-based models were developed with a strictures-and-promoters framework (@lester2020), which is a simplified process-based model especially suitable for situations with limited knowledge. This approach captures the major known limitations and requirements of species, while also maintaining a life-cycle focus. The focus on life cycles gives the opportunity to identify issues such as the most-limiting life stage and understand why apparently favourable conditions at one life stage may not lead to positive outcomes for populations.

Three primary life stages for each species were modeled; adults, regeneration (germination or sprouting), and seedling survival. For each species, we identified major environmental requirements for each life stage from the literature, each with several environmental requirements @tbl-env-reqs. Favourability for adult condition and survival depends on inundation, with strictures arising from excessive inundation (continuous inundation can waterlog or drown roots), the interval between inundation events (most species require inundation at some frequency), and the season in which those events occur. For regeneration, some species have a favourable season, likely due to temperatures, and all require preceding inundation followed by sustained moisture duration over several days. The seedling stage then extends this requirement for soil moisture over months to allow growth past the cotyledon stage and establishment of robust root systems. While these plants need recurrent flooding for establishment and persistence, the seedling stages tend to be sensitive to excessive flooding, and so we also include seedling failure with prolonged inundation.

::: {#tbl-env-reqs}
+-----------+---------------------------------------------------------------------------+---------------------------------------+---------------------------------+----------------------------------------------------------------------------+-------------------------------------------+--------------------------------------------+-------------------------------------------------+
| Species   | Regeneration season                                                       | Regeneration moisture duration (days) | Seedling period length (months) | Seedling excessive inundation (months)                                     | Adult excessive inundation (months)       | Adult inundation interval (months)         | Adult inundation season                         |
+===========+===========================================================================+=======================================+=================================+============================================================================+===========================================+============================================+=================================================+
| Red gum   | Sept-Dec ('Spring to early summer') [@rogers2011; @johns2009]             | 14 @casanova2015                      | 4.5 @roberts2011                | \>2, 'several months' [@johns2009; @dexter1978]                            | 24 @rogers2011                            | 48 @rogers2011                             | July-Dec ('winter to early summer') @rogers2011 |
+-----------+---------------------------------------------------------------------------+---------------------------------------+---------------------------------+----------------------------------------------------------------------------+-------------------------------------------+--------------------------------------------+-------------------------------------------------+
| Black box | May-October (Northern basin), November-March (Southern basin) @rogers2011 | 10 @jensen2008                        | 6 @roberts2011                  | \>2, '70 days' @johns2009                                                  | 5 @rogers2011                             | 96 (8 years) @rogers2011                   | year-round @rogers2011                          |
+-----------+---------------------------------------------------------------------------+---------------------------------------+---------------------------------+----------------------------------------------------------------------------+-------------------------------------------+--------------------------------------------+-------------------------------------------------+
| Coolabah  | Jan-April 'late summer' 'high temperature' [@rogers2011; @roberts2011]    | 14 @casanova2015                      | 6                               | No information [@rogers2011; @durant2016]                                  | No information [@rogers2011; @durant2016] | 240 (20 years) [@rogers2011; @roberts2011] | No data, year-round                             |
|           |                                                                           |                                       |                                 |                                                                            |                                           |                                            |                                                 |
|           |                                                                           |                                       |                                 |                                                                            |                                           |                                            | @rogers2011                                     |
+-----------+---------------------------------------------------------------------------+---------------------------------------+---------------------------------+----------------------------------------------------------------------------+-------------------------------------------+--------------------------------------------+-------------------------------------------------+
| Lignum    | Sept-April 'spring to autumn' [@rogers2011; @casanova2015]                | 14 @casanova2015                      | 3 @capon2009                    | \>1 (any inundation during the seedling period) [@roberts2011; @capon2009] | 12 @rogers2011                            | 120 (10 years) @rogers2011                 | Sept-Dec 'spring- early summer' @rogers2011     |
+-----------+---------------------------------------------------------------------------+---------------------------------------+---------------------------------+----------------------------------------------------------------------------+-------------------------------------------+--------------------------------------------+-------------------------------------------------+

Inundation and soil moisture requirements for four species of wetland-dependent woody vegetation in the Murray-Darling Basin, with references. Because inundation data is bimonthly, seasonality has been approximated as closely as possible given the limitations of those two-month units, and statements such as 'several months of inundation' have been translated to \> 2 months.
:::

Conditions favourable for each life stage were assessed both independently and as part of a life cycle. For example, conditions may be favourable for seedling survival, but if there was no preceding germination, then we would say that conditions were not favourable for overall recruitment. These species can be very long-lived as adults (hundreds of years) and do not have persistent soil seed banks [@roberts2011]. Thus, we consider the 'reference' stage of the population cycle to be adults. To incorporate the life cycle into the stricture calculations, regeneration (germination or sprouting) requires the presence of adults to provide seeds or stems and recruitment requires successful regeneration to provide the initial stock of growing seedlings. Conceptually, new adult recruitment would require these seedlings. However, due to the short data availability relative to adult persistence and the simplicity of the model, we do not create a fully-dynamic population model. Instead, we interpret the outcome of the adults-regeneration-recruitment sequence as favourable conditions for recruitment to the persistent adult stage.

*Feels like discussion, but might be needed here to justify*: The conditions defined here are a subset of the requirements for maintaining viable populations. Other life stages exist, other requirements exist for these life stages, and reality is far more nuanced. However, those chosen here form the primary types of requirements listed in major works about woody vegetation in the basin, [e.g. @rogers2011; @roberts2011] and are those for which there is the best available information in the literature. Most importantly, the requirements here cause very large differences between life stages and species. Thus, while additional research would provide better models, the responses seen here are striking and the qualitative messages are unlikely to change as a more nuanced understanding of the biological processes develops.

### Processing strictures

To assess the

## Habitat favourability

For each species, two sets of wetland types were chosen to comprise 'favourable' habitat types. First, a set of ANAE types with the species' name in the type description was chosen, e.g. for red gum, the matching habitat types were 'River red gum forest riparian zone or floodplain', 'River red gum woodland riparian zone or floodplain', and 'Temporary river red gum swamp'. The second set of habitats recognizes that species may be found in other wetland types than those that bear their name. To identify the set of wetland habitat types where a species might be found, we pulled all records from each species from the Atlas of Living Australia using the 'galah' R package (@westgate2024). We then intersected those records with the ANAE polygons. To avoid selecting spurious matches, we selected those habitat types with \> 0.5% of the records for that species as the set of habitat types where that species consistently occurs. Thus, for each species, we have two sets of habitat types, one defined by *name*, and another defined by *ala*.

Tables here (well, probably in an appendix).

## Environmental data

We used two publicly-available datasets to establish environmental conditions- a two-monthly inundation depth layer @teng2023 and a daily soil moisture layer @frost2018, chosen to capture environmental requirements of the species, with inundation also being the typical hydrological proxy of favourability. Both of these datasets were are raster timeseries, and were processed into a set of 287,680 wetland polygons comprising the Australian National Aquatic Ecosystem Classification (ANAE, @brooks2021) spanning the entire Murray-Darling Basin. Processing rasters into polygons yields several advantages stemming from the habitat classifications. The different wetland polygons define different types, and so flexibly account for areas of different sizes and shapes. Moreover, areas outside wetlands can be ignored. This allows much faster processing while dynamically adjusting grain size to match ecologically-relevant habitat units (see Holt et. al. *in review*). We processed the rasters into the polygons using the eFlowEval R package (Holt et. al. *in review*), yielding inundaton and soil moisture timeseries in each polygon. For inundation, the area inundated \> 5mm depth was calculated for each polygon, while for soil moisture, the area of each polygon with soil moisture between 10% and 30% was calculated, reflecting soil moisture requirements for recruitment and seedling survival @jensen2008.

# Appendix? Notes? Trash

For example, the seedling period is poorly documented, with @jensen2008 stating both 2 years and 'through the summer' for Red Gum, Black, Box, and Coolabah though does not have data. @roberts2011 provides some indications of the ages at which Black Box and Red Gum seedlings have been seen to persist through flooding or drying, though no systematic studies. @capon2009 used three-month old Lignum for a series of experiments showing they were robust to both flooding and drying. However, none of these studies were intended to identify the necessary seedling period, and so are necessarily approximate. What is clear is that soil moisture must persist long enough for seedlings to grow from the cotyledon stage to established plants capable of withstanding both flooding and drought. This establishment requires growing stems, leaves, and a vigorous root system to support the plant. In many species seedlings are known to only be rarely succesful, e.g. only 6 major Coolabah regeneration events have occurred in the basin since 1890 @roberts2011. While the seedling durations chosen here are approximations, shifts in that value do not qualitatively change our results.
