---
title: "Run EWRs"
format: html
editor: visual
---

## Run the EWR tool on pulled gauges

Hoping this works to just bring over from toolkit_use except for the new format tweak.

```{r}
#| echo: false
#| warning: false
#| message: false
library(HydroBOT)
library(dplyr)
library(ggplot2)
library(sf)

# to hopefully speed up the EWR calls
library(future)
library(furrr) 
plan(multisession)

# get directories
source('directorySet.R')
```

Directories

```{r}
# Outer directory for project data
project_dir <- file.path(datOut, 'werpsmoosh')

hydro_dir <- file.path(project_dir, 'hydrographs')

# Generated data
# EWR outputs (will be created here in controller, read from here in aggregator)
ewr_results <- file.path(project_dir, 'module_output', 'EWR')

```

```{r}
outputType <- list('summary', 'yearly')
returnType <- list('none') # list('summary', 'yearly')
```

## Run the toolkit

```{r}
ewr_out <- prep_run_save_ewrs(hydro_dir = hydro_dir, 
                                  output_parent_dir = project_dir, 
                                  outputType = outputType,
                                  returnType = returnType,
                              model_format = 'Standard time-series',
                              rparallel = TRUE)
```

That seems to be the level gauges.

```{r}
ewr_gauges <- get_ewr_gauges()
levels <- ewr_gauges |> filter(gaugetype == 'L')
levels
# Do those all need flow too???
ewr_gauges |> 
  filter(gauge %in% levels$gauge) |> 
  arrange(gauge)
```
