---
title: "Comparer"
format: html
editor: visual
execute: 
  cache: true
---

```{r}
#| include: false
#| 

library(werptoolkitr)
library(dplyr)
library(sf)
library(ggplot2)
library(patchwork)
library(tidyr)
library(CC2)

# get directories
source('directorySet.R')
```

## Paths

I'm going to set this up to dump data to the QAEL WERP share for now. Unfortunately, that calls itself something different for each of us.

```{r}
#| include: false
qaelpath <- myhome
#qaelpath <- path.expand(qaelpath)
datDir <- file.path(qaelpath, "Deakin University/QAEL - MER/Model/dataBase")
datOut <- file.path(qaelpath, "Deakin University/QAEL - SRA - SRA/data_out")
project_dir <- file.path(datOut, 'werpstyle')
hydro_dir <- file.path(project_dir, 'hydrographs')

# Generated data
# EWR outputs (will be created here in controller, read from here in aggregator)
ewr_results <- file.path(project_dir, 'module_output', 'EWR_numeric_gauges')
ewr_results <- file.path(project_dir, 'MANUAL')

# outputs of aggregator. There may be multiple modules
agg_results <- file.path(project_dir, 'aggregator_output_numeric_gauges')

comp_results <- file.path(project_dir, 'comparer_output') 

data_path <- file.path(qaelpath, "Deakin University/QAEL - SRA - SRA/data_out/SRA_analysis/Final_datasets")
```

## Read in agged data

```{r}

#list.files(agg_results)
# sdl_EWRS_agg <- readRDS(file.path(agg_results, "sdl_EWRS_agg", 'achievement_aggregated.rds'))
# #sdl_specific_goal_agg <- readRDS(file.path(agg_results, "sdl_specific_goal_agg", 'achievement_aggregated.rds'))
# #sdl_specific_goal_objective_agg <- readRDS(file.path(agg_results, "sdl_specific_goal_objective_agg", 'achievement_aggregated.rds'))
# sdl_target_agg <- readRDS(file.path(agg_results, "sdl_target_agg", 'achievement_aggregated.rds'))
# # simple_agg <- readRDS(file.path(agg_results, "Simple_agg", 'achievement_aggregated.rds'))


Tagg_gauge_EWRversions <- read.csv(file.path(project_dir, 'MANUAL', 'EWR_summary.csv'))
Timeseries_gauge_EWRversions <- read.csv(file.path(project_dir, 'MANUAL', 'EWR_timeseries.csv'))

#filter EWRs == NA
Tagg_gauge_EWRversions <- filter(Tagg_gauge_EWRversions, !is.na(ewr_achieved))
Timeseries_gauge_EWRversions <- filter(Timeseries_gauge_EWRversions, !is.na(ewr_achieved))

#Clean ewr_code
Tagg_gauge_EWRversions$ewr_code <- sub("-", "_", Tagg_gauge_EWRversions$ewr_code)
Timeseries_gauge_EWRversions$ewr_code <- sub("-", "_", Timeseries_gauge_EWRversions$ewr_code)

#SWITCH CFs
Tagg_gauge_EWRversions <- Tagg_gauge_EWRversions |>
  mutate(ewr_achieved = case_when(ewr_code == "ALT" ~ 1-ewr_achieved,
                                  ewr_code == "CF" ~ 1-ewr_achieved,
                                  ewr_code == "CF1" ~ 1-ewr_achieved,
                                  ewr_code == "CF1_c_P" ~ 1-ewr_achieved,
                                  ewr_code == "CF1_c_S" ~ 1-ewr_achieved,
                                  .default = ewr_achieved))

Timeseries_gauge_EWRversions <- Timeseries_gauge_EWRversions |>
  mutate(ewr_achieved = case_when(ewr_code == "ALT" ~ 1-ewr_achieved,
                                  ewr_code == "CF" ~ 1-ewr_achieved,
                                  ewr_code == "CF1" ~ 1-ewr_achieved,
                                  ewr_code == "CF1_c_P" ~ 1-ewr_achieved,
                                  ewr_code == "CF1_c_S" ~ 1-ewr_achieved,
                                  .default = ewr_achieved))


Timeseries_gauge_EWRversions <- Timeseries_gauge_EWRversions |>
  select(year, ewr_code, scenario, gauge, planning_unit_name, ewr_code_timing, ewr_achieved)

```

## For joining space data and climate categories

```{r}
#Gauge points:
gauges_df <- get_ewr_gauges()|>
  #st_drop_geometry() |>
  mutate(OWNER = case_when(owner == "NSW - NSW Department of Industry – Lands and Water" ~ "NSW",
                           owner == "VIC - Department of Environment, Land, Water and Planning"~ "VIC",
                           owner == "SA - Department of Environment, Water and Natural Resources"~ "SA",
                           owner == "QLD - Department of Natural Resources, Mines and Energy"~ "QLD",
                           owner == NA ~ NA))

#gauges_df_sld <- st_join(gauges_df, sdl_units)
gauges_df_valleys <- st_join(gauges_df, cewo_valleys)


#MAYBE DELETE AFTER HERE:

#Climate categorgy data:
Climate_Categories <- read.csv(file.path(qaelpath, "Deakin University", "QAEL - SRA - SRA", "Climate_Categories_Coloured_2023.csv"), check.names = FALSE)

Climate_Categories <- Climate_Categories |>
  pivot_longer(cols = `Barwon-Darling`:`Total MDB`, names_to = "Climate_category.data", values_to = "Climate_Category")

Climate_Categories <- Climate_Categories |>
  mutate(Climate_Category = factor(Climate_Category, levels = c("Very Dry", "Dry", "Moderate", "Wet", "Very Wet")))

# read in the mapping of sdls to the climate category areas:
Climate_Category_to_polygons <- read.csv(file.path(qaelpath, "Deakin University", "QAEL - SRA - SRA", "Climate_Category_to_polygons.csv"))|>
  dplyr::select(Climate_category.data, SWSDLName)|>
  
  #Climate_Categories_sdl does not have categorys for SA, so should use 'Eastern Mt Lofty Ranges' for SA
  dplyr::mutate(Climate_category_area = case_when(SWSDLName == "South Australian Murray" ~ "Lower Murray",
                                                  SWSDLName == "Eastern Mount Lofty Ranges" ~ "Lower Murray",
                                           SWSDLName == "South Australian Non-Prescribed Areas" ~ "Lower Murray",
                                           SWSDLName == "Marne Saunders" ~ "Lower Murray",
                                           .default = Climate_category.data))|>
  filter(Climate_category_area != "")|>
  filter(SWSDLName != "")|>
  mutate(SWSDLName = case_when(SWSDLName == "Barwon-Darling Watercourse" ~ "Barwon–Darling Watercourse",
                               SWSDLName == "Barwon Darling Watercourse" ~ "Barwon–Darling Watercourse",
                               SWSDLName == "Macquarie-Castlereagh" ~ "Macquarie–Castlereagh",
                               SWSDLName == "Macquarie Castlereagh" ~ "Macquarie–Castlereagh",
                               SWSDLName == "Wimmera Mallee (Surface Water)" ~ "Wimmera–Mallee (Surface Water)",
                               SWSDLName == "Wimmera–Mallee (Surface Water)" ~ "Wimmera–Mallee (Surface Water)",
                               SWSDLName == "Condamine-Balonne" ~ "Condamine–Balonne",
                               SWSDLName == "Condamine Balonne" ~ "Condamine–Balonne",
                               .default = SWSDLName))

# Join polygon data	
Climate_Category_to_polygon_geometry <- left_join(Climate_Category_to_polygons, sdl_units, by = join_by(SWSDLName))
  #Climate_Categories_sdl does not have categorys for SA, so should use 'Eastern Mt Lofty Ranges' for SA

                                                    
# meld polygons
Climate_Category_geometry <- Climate_Category_to_polygon_geometry|>
  group_by(Climate_category_area) |>
  mutate(geometry = st_union(geometry),
         SWSDLName_all = paste(unique(SWSDLName), collapse = ";"),
         Climate_category.data = paste(unique(Climate_category.data), collapse = ""))

# join polygons to climate category data:
Climate_Categories_sdl <- left_join(Climate_Categories, Climate_Category_geometry, by = join_by(Climate_category.data)) |>
  rename(year = `Start of water Year`)

Climate_Categories_sdl



```

## For joining EWR groups and connectivity groups

```{r}
EWRS_df <- Tagg_gauge_EWRversions |>
  distinct(ewr_code) |>
  mutate(ewr_group_temp1 = substr(ewr_code, start = 1, stop = 2)) |>
  mutate(ewr_group_temp2 = substr(ewr_code, start = 1, stop = 1)) |> #DODGY BUT WILL DO FOR NOW
  mutate(ewr_group = case_when(ewr_group_temp2 == "F" ~ ewr_group_temp2, 
                               ewr_group_temp1 == "W-" ~ "LF",
                               .default = ewr_group_temp1)) |>
  mutate(ewr_group = ifelse(is.na(ewr_group), ewr_group_temp1, ewr_group)) |>
  select(-ewr_group_temp1, -ewr_group_temp2)

List_EWRs <- read.csv(file.path(project_dir, "List_EWRs.csv"))

List_EWRs$ewr_code <- sub("-", "_", List_EWRs$ewr_code)
EWRS_df$ewr_code <- sub("-", "_", EWRS_df$ewr_code)


EWRS_df <- left_join(EWRS_df, List_EWRs, by = "ewr_code")


```

## SRA: prep - MANUAL

```{r}
#TIME AGGREGATED (Tagg):
## agregate to EWR codes
Tagg_gauge_EWR <- Tagg_gauge_EWRversions |>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, -ewr_code_timing)))|>
  left_join(EWRS_df)|>
  left_join(gauges_df_valleys, by = "gauge")

## agregate to EWR groups
Tagg_gauge_EWRgroups <- Tagg_gauge_EWR |>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, -ewr_code)))|>
  dplyr::summarise(ewr_achieved = mean(ewr_achieved, na.rm = TRUE))

```

```{r}
#TIMESERIES - Individual EWRS
# GAUGE level

## agregate to EWR codes
Timeseries_gauge_EWR <- Timeseries_gauge_EWRversions |>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, -ewr_code_timing)))|> #didnt work - other variables relating to code_timing
  #dplyr::group_by(year, ewr_code, scenario, gauge, planning_unit_name) |>
  dplyr::summarise(ewr_achieved = max(ewr_achieved, na.rm = TRUE)) |> #USING MAX
  left_join(EWRS_df, by = "ewr_code")

Timeseries_gauge_EWR <- left_join(Timeseries_gauge_EWR, gauges_df_valleys, by = "gauge")

#gauge_EWRS_timeseries <- st_join(gauge_EWRS_timeseries, Climate_Categories)

#individual EWRs
Timeseries_gauge_EWR <- Timeseries_gauge_EWR |>
  ungroup() |>
  st_drop_geometry() |>
  select(-geometry, -planning_unit_name, -planningunitname, -ltwpshortname, -gaugetype, -site, -owner, -OWNER) 

# #add polygons; 
# Timeseries_gauge_EWR <- Timeseries_gauge_EWR |>
#   left_join(Climate_Category_geometry, by = join_by(SWSDLID, SWSDLName, StateID))
# 
# #Then add climate categories (works better than doing both together):
# Timeseries_gauge_EWR <- Timeseries_gauge_EWR |>
#   left_join(Climate_Categories_sdl, by = join_by(year, SWSDLID, SWSDLName, StateID, Climate_category.data, Climate_category_area, geometry, SWSDLName_all))




```

```{r}
#TIMESERIES - GROUPED EWRS
##GAUGE level -  agregate to EWR groups
Timeseries_gauge_EWRgroup <- Timeseries_gauge_EWR |>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, -ewr_code)))|>
  dplyr::summarise(ewr_achieved = mean(ewr_achieved, na.rm = TRUE))
```

```{r}
#TIMESERIES - GROUPED EWRS BY LONG and LATERAL cONNECTIVITY
#(does lat or long connectivity happen at any gauge?)
##GAUGE level -  agregate to EWR groups
Timeseries_gauge_LATERALgroup <- Timeseries_gauge_EWR |>
  dplyr::filter(Lateral_connectivity_including_SF == "Y")|>
  dplyr::select(-Lateral_connectivity_including_SF, -Lateral_connectivity_above_BK, -Lateral_connectivity_including_BK, -Longitudinal_connectivity_CF, -Longitudinal_connectivity_FD, -Notes, -Check, -LTWP)|>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, - ewr_code, -ewr_group)))|>
  dplyr::summarise(ewr_achieved = max(ewr_achieved, na.rm = TRUE))

##GAUGE level -  agregate to EWR groups
Timeseries_gauge_LONGITUDINALgroup <- Timeseries_gauge_EWR |>
  dplyr::filter(Longitudinal_connectivity_CF == "Y" | Longitudinal_connectivity_FD == "Y") |>
  dplyr::select(-Longitudinal_connectivity_CF, -Longitudinal_connectivity_FD, -Lateral_connectivity_above_BK, -Lateral_connectivity_including_BK, -Lateral_connectivity_including_SF, -Notes, -Check, -LTWP)|>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, - ewr_code, -ewr_group)))|>
  dplyr::summarise(ewr_achieved = max(ewr_achieved, na.rm = TRUE))

# VALLEY RESULTS!
Timeseries_ClimateCategoryArea_LATERALgroup <- Timeseries_gauge_LATERALgroup |> 
  ungroup() |>
  dplyr::select(-gauge)|>
  dplyr::group_by(dplyr::across(c(-ewr_achieved)))|>
  dplyr::reframe(ewr_achieved = mean(ewr_achieved, na.rm = TRUE),
                 n_gauges = n())

# VALLEY RESULTS!
Timeseries_ClimateCategoryArea_LONGITUDINALgroup <- Timeseries_gauge_LONGITUDINALgroup |> 
  ungroup() |>
  dplyr::select(-gauge)|>
  dplyr::group_by(dplyr::across(c(-ewr_achieved)))|>
  dplyr::reframe(ewr_achieved = mean(ewr_achieved, na.rm = TRUE),
                 n_gauges = n())

# basin level
Timeseries_Basin_LATERALgroup <- Timeseries_ClimateCategoryArea_LATERALgroup |> 
  ungroup() |>
  dplyr::select(-ValleyName, -ValleyID, -ValleyCode)|>
  dplyr::group_by(year)|>
  dplyr::reframe(ewr_achieved = mean(ewr_achieved, na.rm = TRUE),
                 n_gauges = sum(n_gauges))

# basin level
Timeseries_Basin_LONGITUDINALgroup <- Timeseries_ClimateCategoryArea_LONGITUDINALgroup |> 
  ungroup() |>
  dplyr::select(-ValleyName, -ValleyID, -ValleyCode)|>
  dplyr::group_by(year)|>
  dplyr::reframe(ewr_achieved = mean(ewr_achieved, na.rm = TRUE),
                 n_gauges = sum(n_gauges))


Timeseries_gauge_LATERALgroup <- left_join(Timeseries_gauge_LATERALgroup, gauges_df, by = join_by(gauge))
Timeseries_gauge_LATERALgroup <- Timeseries_gauge_LATERALgroup |>
  rename(geometry_gauge = geometry)
Timeseries_gauge_LATERALgroup <- left_join(Timeseries_gauge_LATERALgroup, cewo_valleys, by = join_by(ValleyName))
Timeseries_gauge_LATERALgroup <- Timeseries_gauge_LATERALgroup |>
  rename(geometry_valley = geometry)

Timeseries_gauge_LONGITUDINALgroup <- left_join(Timeseries_gauge_LONGITUDINALgroup, gauges_df, by = join_by(gauge))
Timeseries_gauge_LONGITUDINALgroup <- Timeseries_gauge_LONGITUDINALgroup |>
  rename(geometry_gauge = geometry)
Timeseries_gauge_LONGITUDINALgroup <- left_join(Timeseries_gauge_LONGITUDINALgroup, cewo_valleys, by = join_by(ValleyName))
Timeseries_gauge_LONGITUDINALgroup <- Timeseries_gauge_LONGITUDINALgroup |>
  rename(geometry_valley = geometry)


saveRDS(Timeseries_gauge_LATERALgroup, file.path(data_path, "Timeseries_gauge_LATERALconnectivity.rds"))
saveRDS(Timeseries_gauge_LONGITUDINALgroup, file.path(data_path, "Timeseries_gauge_LONGITUDINALconnectivity.rds"))

saveRDS(Timeseries_ClimateCategoryArea_LATERALgroup, file.path(data_path, "Timeseries_Valley_LATERALconnectivity.rds"))
saveRDS(Timeseries_ClimateCategoryArea_LONGITUDINALgroup, file.path(data_path, "Timeseries_Valley_LONGITUDINALconnectivity.rds"))

saveRDS(Timeseries_Basin_LATERALgroup, file.path(data_path, "Timeseries_Basin_LATERALconnectivity.rds"))
saveRDS(Timeseries_Basin_LONGITUDINALgroup, file.path(data_path, "Timeseries_Basin_LONGITUDINALconnectivity.rds"))
```

```{r}
# Time aggregation
Tagg_gauge_LATERALgroup <- Timeseries_gauge_LATERALgroup|>
  group_by(gauge)|>
  reframe(ewr_achieved_weighted = weighted.mean(ewr_achieved, year),
          ewr_achieved_unweighted = weighted.mean(ewr_achieved))|>
  left_join(gauges_df_valleys, by = "gauge")

Tagg_gauge_ClimateCategories_LATERALgroup <- Timeseries_gauge_LATERALgroup|>
  group_by(gauge, Climate_Category)|>
  reframe(ewr_achieved_weighted = weighted.mean(ewr_achieved, year),
          ewr_achieved_unweighted = weighted.mean(ewr_achieved))|>
  left_join(gauges_df_valleys, by = "gauge")

Tagg_ClimateCategoryArea_LATERALgroup <- Timeseries_ClimateCategoryArea_LATERALgroup |>
  group_by(Climate_category_area, geometry)|>
  reframe(ewr_achieved_weighted = weighted.mean(ewr_achieved, year),
          ewr_achieved_unweighted = weighted.mean(ewr_achieved))

Tagg_ClimateCategoryArea_ClimateCategories_LATERALgroup <- Timeseries_ClimateCategoryArea_LATERALgroup |>
  group_by(Climate_category_area, Climate_Category, geometry)|>
  reframe(ewr_achieved_weighted = weighted.mean(ewr_achieved, year),
          ewr_achieved_unweighted = weighted.mean(ewr_achieved))
  
Tagg_Basin_LATERALgroup <- Timeseries_Basin_LATERALgroup |>
  group_by(Climate_category.data)|>
  reframe(ewr_achieved_weighted = weighted.mean(ewr_achieved, year),
          ewr_achieved_unweighted = weighted.mean(ewr_achieved))
Tagg_Basin_LATERALgroup <- bind_cols(Tagg_Basin_LATERALgroup, basin)

Tagg_Basin_ClimateCategories_LATERALgroup <- Timeseries_Basin_LATERALgroup |>
  group_by(Climate_category.data, Climate_Category)|>
  reframe(ewr_achieved_weighted = weighted.mean(ewr_achieved, year),
          ewr_achieved_unweighted = weighted.mean(ewr_achieved))
Tagg_Basin_ClimateCategories_LATERALgroup <- bind_cols(Tagg_Basin_ClimateCategories_LATERALgroup, basin)



```

```{r}
#individual EWR
# Climate_category_area level
Timeseries_ClimateCategoryArea_EWR <- Timeseries_gauge_EWR |> 
  ungroup() |>
  dplyr::select(-gauge, -SWSDLID, -SWSDLName, -StateID, -Climate_category.data)|>
  dplyr::group_by(dplyr::across(c(-ewr_achieved)))|>
  dplyr::reframe(ewr_achieved = mean(ewr_achieved, na.rm = TRUE))

#EWR GROUP
# SWSDLName level
Timeseries_ClimateCategoryArea_EWRgroup <- Timeseries_ClimateCategoryArea_EWR |>
  dplyr::group_by(dplyr::across(c(-ewr_achieved, -ewr_code)))|>
  dplyr::summarise(ewr_achieved = mean(ewr_achieved, na.rm = TRUE))
```

```{r}
#Aggregating time
Tagg_ClimateCategoryArea_EWRgroup <- Timeseries_ClimateCategoryArea_EWRgroup |> 
  ungroup() |>
  dplyr::group_by(dplyr::across(c( -ewr_achieved, -year)))|>
  dplyr::reframe(ewr_achieved = mean(ewr_achieved, na.rm = TRUE),
                 n_years = n())
```

## CHECKING MAPS

```{r}
temp <- Timeseries_gauge_LATERALgroup |>
  ungroup()|>
  distinct(gauge, ValleyName, geometry_gauge, geometry_valley)

Valleys_included <- unique(temp$ValleyName)

Valleys_excluded <- filter(cewo_valleys, !ValleyName %in% Valleys_included)
Valleys_excluded <- Valleys_excluded$ValleyName

gauges_df
gauges_df_distinct <- gauges_df|>
  distinct(gauge, .keep_all = TRUE)
  
ggplot() +
  geom_sf(data = temp,  aes(geometry = geometry_valley), fill = "grey")+
  geom_sf(data = gauges_df_distinct,  aes(geometry = geometry))+
  geom_sf(data = cewo_valleys, aes(geometry = geometry), fill = NA)+
  geom_sf(data = sdl_units, aes(geometry = geometry), colour = "red", fill = NA)+
  #geom_sf_text(data = filter(cewo_valleys, !ValleyName %in% Valleys_included), aes(geometry = geometry, label = ValleyName), colour = "red", size = 3)+
  #geom_sf_text(aes(label = ValleyName), colour = "red", size = 3)+
  theme_werp_toolkit() +
  paletteer::scale_fill_paletteer_c('grDevices::Viridis',
                      limits = c(0,1)) +
  labs(fill = "Lateral connectivity IS", y = "", x = "", colour = "")



temp <- Tagg_gauge_EWRversions |>
  distinct(gauge, planning_unit_name, .keep_all = TRUE)|>
  left_join(gauges_df, by = join_by(gauge, "planning_unit_name" == "planningunitname"))|>
  left_join(gauges_df_valleys)
```
## Checking EWRS
```{r}
#checking that i have some lateral and longitudinal EWRs for each catchment:


temp <- Timeseries_gauge_EWR |>
  group_by(ValleyName)|>
  filter(paste(unique(Longitudinal_connectivity_CF), collapse = "") == "N" & paste(unique(Longitudinal_connectivity_FD), collapse = "") == "N")

Valleys_no_long <- unique(temp$ValleyName)


temp <- Timeseries_gauge_EWR |>
  group_by(ValleyName)|>
  filter(paste(unique(Lateral_connectivity_including_SF), collapse = "") == "N" & paste(unique(Lateral_connectivity_including_SF), collapse = "") == "N")

unique(temp$ValleyName)


#FOR LOOKING AT EWRS
EWR_table <- get_ewr_table()
EWR_table <- left_join(EWR_table, gauges_df_valleys, by = c("Gauge" = "gauge"))
EWR_table$ewr_code <- sub("_[^_]+$", "", EWR_table$Code)

temp <- EWR_table |>
  filter(ValleyName %in% Valleys_no_long)

```




```

