---
title: "EWR tables"
format: html
editor: visual
---

## Finding EWR table for lowest gauges

```{r}
library(werptoolkitr)
library(sf)
library(dplyr)
library(ggplot2)
```

Just do it for one catchment. Find the lowest gauge in Macquarie

```{r}
macshp <- sdl_units |> 
  dplyr::filter(grepl('Macq', SWSDLName))

macrivers <- st_intersection(basin_rivers, macshp)

macgauges <- get_ewr_gauges() |> 
  st_intersection(macshp)
```

Plot to figure it out

```{r}
ggplot() +
  geom_sf(data = macshp) +
  geom_sf(data = macrivers) + 
  geom_sf(data = macgauges)+
  geom_sf_label(data = macgauges, mapping = aes(label = gauge))
```

Most downstream is 422028

```{r}
mac_ewrtab <- get_ewr_table() |> 
  dplyr::filter(Gauge == '422028')
  
```

Get relevant EWRs

```{r}
mac_simple <- mac_ewrtab |> 
  # dplyr::filter(grepl('^SF|^LF|BK|OB', Code)) |> 
  dplyr::select(Gauge, Code, StartMonth, EndMonth, TargetFrequency, EventsPerYear, Duration, MinSpell, FlowThresholdMin, FlowThresholdMax, `MaxInter-event`)

attributes(mac_simple)$pandas.index <- NULL
row.names(mac_simple) <- NULL
```

```{r}
mac_simple |> 
  knitr::kable()
```

```{r}
mac_simple |> 
  readr::write_csv('macquarie_ds_ewrs.csv')
```
